// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
// / import 'firebase_options.dart';
// / // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEwyZfB2A7paMJCnYCEEellbYwuaEtyH4',
    appId: '1:690244741229:web:15240f5cb81809af54f764',
    messagingSenderId: '690244741229',
    projectId: 'personal-finance-tracker-4f122',
    authDomain: 'personal-finance-tracker-4f122.firebaseapp.com',
    storageBucket: 'personal-finance-tracker-4f122.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMRt9k8QDXajIfgAtMYS3fHchvhOrBrqs',
    appId: '1:690244741229:android:31a5344af8fe506354f764',
    messagingSenderId: '690244741229',
    projectId: 'personal-finance-tracker-4f122',
    storageBucket: 'personal-finance-tracker-4f122.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDb15hR9QkuQOdXkE_-eupgX5hWlUQg2wM',
    appId: '1:690244741229:ios:d731ba2e5ab9003a54f764',
    messagingSenderId: '690244741229',
    projectId: 'personal-finance-tracker-4f122',
    storageBucket: 'personal-finance-tracker-4f122.firebasestorage.app',
    iosBundleId: 'com.example.personalFinanceTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDb15hR9QkuQOdXkE_-eupgX5hWlUQg2wM',
    appId: '1:690244741229:ios:d731ba2e5ab9003a54f764',
    messagingSenderId: '690244741229',
    projectId: 'personal-finance-tracker-4f122',
    storageBucket: 'personal-finance-tracker-4f122.firebasestorage.app',
    iosBundleId: 'com.example.personalFinanceTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEwyZfB2A7paMJCnYCEEellbYwuaEtyH4',
    appId: '1:690244741229:web:9d3572a48031ce5454f764',
    messagingSenderId: '690244741229',
    projectId: 'personal-finance-tracker-4f122',
    authDomain: 'personal-finance-tracker-4f122.firebaseapp.com',
    storageBucket: 'personal-finance-tracker-4f122.firebasestorage.app',
  );
}
